[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start --workspace=apps/backend"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "backend"
source = "."

[[services]]
name = "postgres"