[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm run start --workspace=apps/backend"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "backend"
source = "."

[[services]]
name = "postgres"